name: Build and Deploy Hugo Site

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.BLOG_GITHUB_ACTION }}
          ref: master
          fetch-depth: 0
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.148.2"
          extended: true
          fallback: true
          
      - name: Build site
        run: |
          # 添加详细日志输出
          hugo version
          hugo --minify --gc --cleanDestinationDir --verbose
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BLOG_GITHUB_ACTION }}
          external_repository: ha7m010/ha7m010.github.io
          publish_dir: ./public
          publish_branch: main
          keep_files: true
          commit_message: "Deploy from ${{ github.sha }}"