name: Build and Deploy Hugo Site

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      # 1. 检出源码（包含子模块）
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.BLOG_GITHUB_ACTION }}
          ref: master
          fetch-depth: 0
          
      # 2. 安装 Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.148.2"
          extended: true
          
      # 3. 修复构建步骤 ✅
      - name: Build site
        run: |
          echo "=== 打印 Hugo 版本信息 ==="
          hugo version
          
          echo "=== 开始构建网站 ==="
          # 移除了不支持的 --verbose 标志
          hugo \
            --minify \
            --gc \
            --cleanDestinationDir \
            --logLevel info  # 使用支持的日志级别 ✅
      
      # 4. 部署到 Pages 仓库
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BLOG_GITHUB_ACTION }}
          external_repository: ha7m010/ha7m010.github.io
          publish_dir: ./public
          publish_branch: main
          keep_files: true
          commit_message: "Deploy from ${{ github.sha }}"